window.DAILY1000_STORY_DECK = Object.freeze([
  {
    id: "gothic-closed-wing",
    genre: "gothic mystery",
    modes: ["balanced", "dark", "strange"], intensity: 4,
    mood: "eerie and restrained",
    character: "an archivist accused of stealing evidence",
    setting: "a decaying estate opened for one final inventory",
    desire: "to clear their name before the estate is sold",
    conflict: "the missing evidence would also expose the person who protected them years ago",
    element: "fresh dust disturbed beneath one locked door",
    ending: "a bittersweet revelation",
    premise: "An archivist accused of stealing evidence is hired to inventory a decaying estate before its sale. In a wing the family insists has been sealed for decades, fresh disturbances point toward the document that could clear the archivist's name. Recovering it would also expose the person who protected them years ago."
  },
  {
    id: "gothic-last-performance",
    genre: "gothic mystery",
    modes: ["balanced", "dark"], intensity: 3,
    mood: "melancholy and luminous",
    character: "a retired opera singer",
    setting: "a theater reopening for a memorial performance",
    desire: "to perform one final time without revealing why they retired",
    conflict: "the memorial honors the understudy whose career they quietly destroyed",
    element: "powder from old stage makeup on clean towels",
    ending: "a confession that changes the meaning of the story",
    premise: "A retired opera singer agrees to perform at the reopening of the theater where their career ended. The memorial is for an understudy whose disappearance made that career possible, and preparations begin uncovering evidence of the singer's role. They must choose between preserving the last beautiful version of their life and telling the audience what really happened."
  },
  {
    id: "cozy-bakery-charm",
    genre: "cozy fantasy",
    modes: ["balanced", "cozy"], intensity: 2,
    mood: "warm but bittersweet",
    character: "a baker whose magic only works for other people",
    setting: "a village bakery during the week of its harvest festival",
    desire: "to keep the bakery from closing after the festival",
    conflict: "the winning recipe depends on help from the rival buying the building",
    element: "flour handprints on the back door",
    ending: "a hopeful final image",
    premise: "A baker can enchant food to reveal what other people need, but the magic never answers questions about the baker's own life. During the village harvest festival, saving the bakery requires a winning recipe and the cooperation of the rival who plans to buy the building. Working together reveals that each has misunderstood what the other is trying to preserve."
  },
  {
    id: "cozy-library-weather",
    genre: "cozy fantasy",
    modes: ["balanced", "cozy", "strange"], intensity: 2,
    mood: "wonder-filled",
    character: "a librarian serving a town that schedules its weather",
    setting: "a public library during an unscheduled week of rain",
    desire: "to keep the library open long enough to shelter the town",
    conflict: "the weather clerk responsible is the librarian's frightened younger sibling",
    element: "damp return slips tucked inside dry books",
    ending: "a quiet emotional realization",
    premise: "In a town where weather is booked months in advance, an unscheduled week of rain floods every public building except the library. The librarian turns it into a shelter while quietly investigating the failed forecast. The mistake leads to their younger sibling, whose attempt to help the town has created a problem neither of them can solve alone."
  },
  {
    id: "realism-family-house",
    genre: "literary realism",
    modes: ["balanced", "cozy"], intensity: 2,
    mood: "nostalgic and intimate",
    character: "a recently divorced parent",
    setting: "the family home being emptied after a funeral",
    desire: "to leave with one honest memory of the person who died",
    conflict: "their sibling needs the same memory to remain a lie",
    element: "small apologies written in cookbook margins",
    ending: "a quiet emotional realization",
    premise: "While clearing the family home after a funeral, a recently divorced parent finds apologies written in the margins of a heavily used cookbook. The notes contradict the story both siblings have told about their childhood. One wants an honest memory to carry away; the other needs the old version to survive the sale of the house."
  },
  {
    id: "realism-night-bus",
    genre: "literary realism",
    modes: ["balanced"], intensity: 3,
    mood: "quietly devastating",
    character: "a night-shift nurse nearing retirement",
    setting: "the final bus route home before a hospital closes",
    desire: "to say goodbye to a former patient without reopening an old mistake",
    conflict: "the patient remembers the night differently and wants the nurse to admit it publicly",
    element: "bus transfers folded into precise squares",
    ending: "a bittersweet revelation",
    premise: "On the last night before a neighborhood hospital closes, a nurse nearing retirement takes the familiar bus route home with a former patient. The patient wants a public account of the mistake that changed both their lives; the nurse wants a private goodbye. Over the length of the route, each must decide what acknowledgment can repair and what it cannot."
  },
  {
    id: "space-garden-sabotage",
    genre: "space opera",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "urgent and cinematic",
    character: "an orbital mechanic raised by the ship's gardeners",
    setting: "a colony ship garden failing days before landfall",
    desire: "to save the crop that will feed the new colony",
    conflict: "the sabotage was ordered to prevent settlement on an inhabited world",
    element: "green stains on maintenance gloves",
    ending: "a victory with a cost",
    premise: "Days before a colony ship reaches its destination, the garden that will feed the settlement begins to fail. An orbital mechanic raised by the gardeners traces the damage to deliberate changes in the life-support system. Stopping the sabotage could save thousands, but the saboteur claims the chosen world is already inhabited and the mission leadership buried the evidence."
  },
  {
    id: "space-ceasefire-courier",
    genre: "space opera",
    modes: ["balanced", "romantic"], intensity: 4,
    mood: "tense and claustrophobic",
    character: "a diplomat raised on a colony ship",
    setting: "a neutral station during the final hour of a ceasefire",
    desire: "to deliver a message that could end the war",
    conflict: "the message proves their own government began the conflict",
    element: "coffee rings spreading across a star chart",
    ending: "a tragic sacrifice",
    premise: "A diplomat has one hour to cross a neutral station and deliver terms that could end a planetary war. The sealed evidence accompanying the terms proves their own government manufactured the first attack. Releasing it may secure peace while destroying the diplomat's family, citizenship, and only route home."
  },
  {
    id: "horror-memory-clinic",
    genre: "psychological horror",
    modes: ["balanced", "dark", "strange"], intensity: 4,
    mood: "unsettling but beautiful",
    character: "a therapist who records every session by hand",
    setting: "an isolated sleep clinic during a winter storm",
    desire: "to identify why every patient is describing the same childhood room",
    conflict: "the room appears in the therapist's own notes from years they cannot remember",
    element: "indentations left on blank notebook pages",
    ending: "an unresolved mystery",
    premise: "During a winter storm, patients at an isolated sleep clinic begin describing the same childhood room despite having no connection to one another. Their therapist discovers the room in old session notes written in their own hand, dated during years they cannot remember. Continuing the investigation may restore those years or prove that the therapist created the memory in every patient."
  },
  {
    id: "horror-perfect-neighbor",
    genre: "psychological horror",
    modes: ["balanced", "dark"], intensity: 3,
    mood: "eerie and restrained",
    character: "a tenant recovering from a public breakdown",
    setting: "an apartment building where every neighbor follows the same routine",
    desire: "to prove they are capable of living independently",
    conflict: "questioning the routine will look exactly like another breakdown",
    element: "groceries arranged in identical order outside each door",
    ending: "a shocking twist",
    premise: "A tenant recovering from a public breakdown moves into a building whose residents follow reassuringly predictable routines. Small deviations reveal that the routines are coordinated and that the newest tenant is the only person not following a script. Investigating could prove something is wrong, but every accusation strengthens the case that they should not be living alone."
  },
  {
    id: "magic-town-grief",
    genre: "magical realism",
    modes: ["balanced", "cozy", "strange"], intensity: 2,
    mood: "melancholy and luminous",
    character: "a postal clerk returning after their mother's death",
    setting: "a town where undelivered letters appear as fog",
    desire: "to finish sorting their mother's unopened mail",
    conflict: "one letter contains the apology they spent years demanding",
    element: "blue stamps carefully removed from envelopes",
    ending: "a bittersweet revelation",
    premise: "In a town where undelivered letters gather as morning fog, a postal clerk returns to sort their mother's unopened mail. Clearing the fog requires delivering each letter, including an apology the clerk spent years demanding and no longer knows how to receive. The final delivery changes less than they hoped and more than they expected."
  },
  {
    id: "magic-missing-tuesday",
    genre: "magical realism",
    modes: ["balanced", "strange"], intensity: 3,
    mood: "dreamlike and strange",
    character: "a school secretary who remembers one extra day each week",
    setting: "a neighborhood school preparing for graduation",
    desire: "to find the student who exists only on the missing day",
    conflict: "restoring that day would erase the secretary's present family",
    element: "attendance sheets with one line cut away",
    ending: "a circular ending that echoes the first line",
    premise: "A school secretary remembers a Tuesday that vanishes from everyone else's week. On that missing day, one student continues attending classes and asking why nobody comes back. Restoring Tuesday could rescue the student, but the secretary learns that the life and family they know were created by its disappearance."
  },
  {
    id: "romcom-wrong-wedding",
    genre: "romantic comedy",
    modes: ["balanced", "cozy", "romantic"], intensity: 2,
    mood: "romantic and awkward",
    character: "a wedding photographer who hates improvising",
    setting: "a courthouse hosting two weddings with identical surnames",
    desire: "to complete the job without another viral mistake",
    conflict: "the only person who can sort out the mix-up is the charming witness they publicly blamed",
    element: "name cards corrected in different handwriting",
    ending: "a hopeful final image",
    premise: "A wedding photographer determined to avoid another viral mistake discovers that two courthouse weddings with identical surnames have exchanged witnesses, flowers, and one nervous groom. The only person calm enough to untangle it is the witness the photographer publicly blamed. Fixing the ceremonies requires them to work together while every correction creates a more embarrassing misunderstanding."
  },
  {
    id: "romcom-last-bar",
    genre: "romantic comedy",
    modes: ["balanced", "romantic"], intensity: 2,
    mood: "wry and fast-moving",
    character: "a public defender organizing a terrible first date",
    setting: "a neighborhood bar on its final night",
    desire: "to prove they can keep work from consuming every relationship",
    conflict: "their date is representing the landlord closing the bar",
    element: "cocktail napkins covered in competing to-do lists",
    ending: "a confession that changes the meaning of the story",
    premise: "A public defender chooses a neighborhood bar's final night for a first date meant to prove work no longer controls their life. Their date arrives directly from representing the landlord who is closing the bar. When the regulars mistake them for a team capable of saving it, both must decide how much truth the evening can survive."
  },
  {
    id: "noir-funeral-ledger",
    genre: "noir detective story",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "bleak and elegant",
    character: "a detective who now investigates insurance fraud",
    setting: "a funeral home preparing the wrong person's service",
    desire: "to correct the identity before the family arrives",
    conflict: "the error conceals a fraud committed by the detective's former partner",
    element: "carbon copies with one address typed twice",
    ending: "a final betrayal",
    premise: "An insurance investigator discovers that a funeral home is preparing a service under the wrong identity. Correcting the record would expose a profitable scheme built by the investigator's former police partner. With the family already arriving, the investigator must choose which truth to reveal first and who will pay for the delay."
  },
  {
    id: "noir-museum-alibi",
    genre: "noir detective story",
    modes: ["balanced", "dark"], intensity: 3,
    mood: "funny with a dark edge",
    character: "a disgraced journalist writing museum captions",
    setting: "a museum gallery after closing",
    desire: "to verify an alibi that could restore their career",
    conflict: "the alibi clears a killer and implicates the source who once saved them",
    element: "labels replaced with slightly different dates",
    ending: "a victory with a cost",
    premise: "A disgraced journalist working nights on museum captions notices that dates in one exhibition have been quietly altered. The original dates verify an alibi that could restore the journalist's career, but they also clear a suspected killer and implicate the source who once saved the journalist from prison."
  },
  {
    id: "survival-greenhouse-vote",
    genre: "post-apocalyptic survival",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "tense and claustrophobic",
    character: "a former paramedic managing the settlement's greenhouse",
    setting: "a stadium settlement during its first winter",
    desire: "to keep the last viable crop alive until spring",
    conflict: "the water needed for the crop is being withheld for injured outsiders",
    element: "condensation wiped from the same pane each morning",
    ending: "a victory with a cost",
    premise: "During a settlement's first winter, a former paramedic must keep the last viable crop alive with three days of water remaining. The council has secretly diverted the water to injured outsiders waiting beyond the gates. Saving either group is possible; admitting that both cannot be saved may destroy the settlement before hunger does."
  },
  {
    id: "survival-road-map",
    genre: "post-apocalyptic survival",
    modes: ["balanced", "dark"], intensity: 5,
    mood: "urgent and cinematic",
    character: "a scavenger mapping the remaining safe roads",
    setting: "an evacuation checkpoint abandoned mid-convoy",
    desire: "to lead a group of children to the coast",
    conflict: "the safest route passes through the community that exiled them",
    element: "mile markers repainted with household colors",
    ending: "a hopeful final image",
    premise: "A scavenger finds a group of children stranded at an evacuation checkpoint and agrees to lead them to the coast. The only route still open crosses the community that exiled the scavenger for a choice everyone remembers differently. Returning may save the children while surrendering the freedom exile finally provided."
  },
  {
    id: "myth-ferryman-daughter",
    genre: "myth retelling",
    modes: ["balanced", "strange", "dark"], intensity: 4,
    mood: "melancholy and luminous",
    character: "the daughter of a ferryman who carries the dead",
    setting: "a river crossing during a strike among the gods",
    desire: "to bring one living passenger home",
    conflict: "the passenger is responsible for the ferryman's death",
    element: "coins polished smooth by nervous hands",
    ending: "a tragic sacrifice",
    premise: "When the gods stop receiving the dead, a ferryman's daughter inherits a river crowded with stranded souls. One living passenger offers to end the strike in exchange for passage home. The passenger can restore the world, but is also responsible for the ferryman's death."
  },
  {
    id: "myth-echo-witness",
    genre: "myth retelling",
    modes: ["balanced", "romantic", "strange"], intensity: 3,
    mood: "tender and hopeful",
    character: "a court musician cursed to repeat other people's words",
    setting: "a palace trial where testimony must be sung",
    desire: "to testify for the person they love",
    conflict: "speaking the truth will repeat the accusation that condemns them",
    element: "breaths marked between lines of music",
    ending: "a transformation",
    premise: "A court musician who can only repeat words spoken by others must testify in a trial where every statement is sung. The musician can save the person they love only by repeating the accusation that will condemn them. Finding a truthful arrangement of borrowed words becomes an act of both law and rebellion."
  },
  {
    id: "history-printer-election",
    genre: "historical fiction",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "urgent and cinematic",
    character: "an apprentice printer",
    setting: "a print shop under government surveillance before an election",
    desire: "to publish testimony before the presses are seized",
    conflict: "the censor assigned to the shop is their older brother",
    element: "ink on cuffs that were clean at breakfast",
    ending: "a victory with a cost",
    premise: "On the night before a disputed election, an apprentice printer receives testimony proving that the leading candidate ordered a deadly crackdown. Government officers will seize the presses at dawn, and the censor assigned to watch the shop is the apprentice's older brother. Printing the account may change the vote while condemning the brother as an accomplice."
  },
  {
    id: "history-quarantine-inn",
    genre: "historical fiction",
    modes: ["balanced", "romantic"], intensity: 3,
    mood: "warm but bittersweet",
    character: "a war widow running a boarding house",
    setting: "a port city sealed by quarantine",
    desire: "to keep every tenant housed until the gates reopen",
    conflict: "one tenant is the deserter accused of abandoning the widow's spouse",
    element: "meal tickets reused until the ink fades",
    ending: "a bittersweet revelation",
    premise: "During a port-city quarantine, a war widow keeps a crowded boarding house operating on credit and dwindling food. A new tenant is the deserter accused of abandoning the widow's spouse in battle. Protecting the household requires learning whether the accusation is true before frightened neighbors identify him."
  },
  {
    id: "cyber-memory-courier",
    genre: "cyberpunk thriller",
    modes: ["balanced", "dark", "strange"], intensity: 5,
    mood: "urgent and cinematic",
    character: "a courier with an illegal memory implant",
    setting: "a transit hub under corporate lockdown",
    desire: "to deliver evidence before the implant overwrites it",
    conflict: "the evidence proves the courier volunteered for the crime they are exposing",
    element: "arrival boards lagging by exactly eleven seconds",
    ending: "a shocking twist",
    premise: "A courier carrying evidence inside an illegal memory implant is trapped in a transit hub during a corporate lockdown. The implant is overwriting the evidence with the courier's own suppressed memories. Reaching the recipient may expose the corporation, but the recovered memory suggests the courier volunteered for the operation they now call a crime."
  },
  {
    id: "cyber-flooded-district",
    genre: "cyberpunk thriller",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "bleak and elegant",
    character: "a climate refugee repairing municipal drones",
    setting: "a flooded district scheduled for automated demolition",
    desire: "to prove the neighborhood is still occupied",
    conflict: "the official population data was erased by someone the refugee trusts",
    element: "handwritten apartment numbers above digital locks",
    ending: "a final betrayal",
    premise: "A climate refugee repairing municipal drones discovers that their flooded district has been classified as empty and scheduled for demolition. Proving that people still live there requires restoring population records erased from the city network. The deletion credentials belong to the organizer who helped the refugee settle there."
  },
  {
    id: "family-recipe-sale",
    genre: "family drama",
    modes: ["balanced", "cozy"], intensity: 2,
    mood: "warm but bittersweet",
    character: "a chef returning home after fifteen years",
    setting: "the family's restaurant during its final dinner service",
    desire: "to cook one meal everyone remembers the same way",
    conflict: "the recipe was created by the relative the family erased from its history",
    element: "orders rewritten in a familiar slanted hand",
    ending: "a confession that changes the meaning of the story",
    premise: "A chef returns after fifteen years to cook the family's restaurant's final dinner service. The signature recipe everyone claims as an inheritance was actually created by a relative whose name has been removed from every menu and photograph. Serving it one last time forces the family to decide whether tradition matters more than attribution."
  },
  {
    id: "family-storage-unit",
    genre: "family drama",
    modes: ["balanced"], intensity: 3,
    mood: "quietly devastating",
    character: "two siblings who have not spoken since their father's trial",
    setting: "a storage unit that must be emptied by sunset",
    desire: "to divide the belongings without discussing the trial",
    conflict: "one ordinary box proves both siblings lied under oath",
    element: "masking-tape labels written over older labels",
    ending: "a quiet emotional realization",
    premise: "Two siblings who have not spoken since their father's trial must empty his storage unit by sunset. They agree to divide the belongings without discussing the case, until one ordinary box proves that both gave false testimony for different reasons. Neither can tell the full truth without changing what the other sacrificed."
  },
  {
    id: "academia-stolen-thesis",
    genre: "dark academia",
    modes: ["balanced", "dark", "strange"], intensity: 4,
    mood: "eerie and restrained",
    character: "a scholarship student cataloging a famous professor's papers",
    setting: "a university archive closed for winter break",
    desire: "to secure the recommendation that will fund another year",
    conflict: "the professor's celebrated theory was stolen from the student's missing parent",
    element: "citation cards trimmed to remove one line",
    ending: "a confession that changes the meaning of the story",
    premise: "Over winter break, a scholarship student catalogs the papers of the professor whose recommendation controls their funding. The archive reveals that the professor's celebrated theory was taken from the student's missing parent. Exposing the theft could restore a stolen legacy while ending the student's education."
  },
  {
    id: "academia-secret-society",
    genre: "dark academia",
    modes: ["balanced", "dark"], intensity: 5,
    mood: "tense and claustrophobic",
    character: "a junior lecturer denied tenure",
    setting: "a college dining hall during a secret alumni vote",
    desire: "to learn who destroyed their career",
    conflict: "the vote can be reversed only by taking the place of the colleague it will ruin",
    element: "wine glasses placed at empty seats",
    ending: "a final betrayal",
    premise: "A junior lecturer denied tenure discovers that the decision was made during a private alumni vote held beneath the college dining hall. The vote can still be reversed, but only if the lecturer presents evidence that will destroy the colleague selected in their place. That colleague is the only person who warned them the system was rigged."
  },
  {
    id: "western-water-deed",
    genre: "western",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "bleak and elegant",
    character: "a deputy ordered to arrest a childhood friend",
    setting: "a drought-stricken town awaiting a land-company hearing",
    desire: "to keep the town's only well in public hands",
    conflict: "the friend stole the deed that proves the company's legal claim",
    element: "water measurements penciled inside a hatband",
    ending: "a victory with a cost",
    premise: "A deputy is ordered to arrest the childhood friend who stole the deed to a drought-stricken town's only well. The theft may be the only way to prevent a land company from winning the next morning's hearing. Enforcing the law preserves the deputy's authority; breaking it may preserve the town."
  },
  {
    id: "western-photograph",
    genre: "western",
    modes: ["balanced"], intensity: 3,
    mood: "melancholy and luminous",
    character: "a traveling photographer who stages heroic portraits",
    setting: "a mining town after a fatal tunnel collapse",
    desire: "to make one truthful image before leaving town",
    conflict: "the truthful image would prove the celebrated rescue was staged",
    element: "silver dust caught in portrait backdrops",
    ending: "a bittersweet revelation",
    premise: "A traveling photographer is hired to create heroic portraits after a mining disaster. While arranging the survivors, the photographer realizes that the celebrated rescue was staged after several workers were deliberately abandoned. One truthful image could expose the company, but only by using the survivors who asked not to be seen."
  },
  {
    id: "fairy-unwanted-blessing",
    genre: "fairy tale retelling",
    modes: ["balanced", "strange", "romantic"], intensity: 3,
    mood: "unsettling but beautiful",
    character: "the youngest child blessed to be loved by everyone",
    setting: "a kingdom preparing for the child's arranged marriage",
    desire: "to learn whether anyone has ever chosen them freely",
    conflict: "breaking the blessing will also free the ruler who uses it to control the court",
    element: "compliments repeated in exactly the same order",
    ending: "a transformation",
    premise: "The youngest royal child was blessed at birth to be loved by everyone and has never heard an honest refusal. On the eve of an arranged marriage, they discover that the blessing also keeps the court obedient to the ruler. Breaking it could reveal whether anyone loves them freely while releasing every resentment the kingdom has been unable to express."
  },
  {
    id: "fairy-wolf-testimony",
    genre: "fairy tale retelling",
    modes: ["balanced", "dark", "strange"], intensity: 4,
    mood: "eerie and restrained",
    character: "a village seamstress who repairs ceremonial cloaks",
    setting: "a forest court trying the wolf from an old story",
    desire: "to testify about what happened without becoming part of the tale",
    conflict: "the village's safety depends on preserving the false version",
    element: "red thread pulled from every witness's clothing",
    ending: "a circular ending that echoes the first line",
    premise: "A seamstress is summoned to a forest court to testify at the wolf's trial because she repaired the cloaks worn by every witness. The evidence in the seams contradicts the village's famous account of the attack. Telling the truth may free the wolf while ending the bargain that has kept the village safe."
  },
  {
    id: "supernatural-lost-coat",
    genre: "supernatural slice of life",
    modes: ["balanced", "cozy"], intensity: 1,
    mood: "tender and hopeful",
    character: "a night-shift nurse working the hospital's final week",
    setting: "a nearly empty hospital lost-and-found room",
    desire: "to return every remaining item before the building closes",
    conflict: "one coat belongs to a patient whose family was never told the truth",
    element: "claim tickets softened from being handled",
    ending: "a quiet emotional realization",
    premise: "During a hospital's final week, a night-shift nurse tries to return everything left in the lost-and-found room. One coat is repeatedly claimed by a patient who died years earlier and wants it delivered to a family who was never told the truth. The nurse can complete the small request only by admitting what the hospital asked its staff to hide."
  },
  {
    id: "supernatural-ghost-kitchen",
    genre: "supernatural slice of life",
    modes: ["balanced", "cozy", "romantic"], intensity: 2,
    mood: "funny with a dark edge",
    character: "a chef running the last service at a neighborhood restaurant",
    setting: "a kitchen crowded with former employees' ghosts",
    desire: "to close the restaurant without repeating the owner's mistakes",
    conflict: "the ghosts disagree about which mistake mattered most",
    element: "prep lists corrected in several generations of handwriting",
    ending: "a hopeful final image",
    premise: "On a neighborhood restaurant's final night, the kitchen fills with the ghosts of former employees offering contradictory advice. The chef wants to close with dignity and avoid repeating the owner's mistakes, but every ghost remembers a different harm. Serving the last table requires choosing which debt can still be paid."
  },
  {
    id: "politics-ceasefire-copy",
    genre: "political intrigue",
    modes: ["balanced", "dark"], intensity: 5,
    mood: "tense and claustrophobic",
    character: "a palace translator trusted by both negotiating sides",
    setting: "an embassy during the final hour of a ceasefire",
    desire: "to keep the agreement alive until it is signed",
    conflict: "one mistranslated sentence benefits the translator's occupied homeland",
    element: "corrections made in ink of two slightly different colors",
    ending: "a final betrayal",
    premise: "During the final hour of ceasefire negotiations, a palace translator discovers that one sentence has been deliberately mistranslated in every official copy. Correcting it may collapse the agreement; leaving it favors the translator's occupied homeland and guarantees a future conflict. Both delegations trust the translator to declare which text is authentic."
  },
  {
    id: "politics-election-archive",
    genre: "political intrigue",
    modes: ["balanced", "dark"], intensity: 4,
    mood: "wry and fast-moving",
    character: "an archivist preparing records for a reform candidate",
    setting: "a courthouse during a disputed election recount",
    desire: "to release evidence before the recount ends",
    conflict: "the evidence proves the reform candidate won by committing the same fraud they condemned",
    element: "page numbers added after documents were bound",
    ending: "a victory with a cost",
    premise: "During a disputed election recount, an archivist finds records proving that the reform candidate did win, but used the same fraud they publicly condemned. Releasing the evidence will defeat the corrupt incumbent and discredit the movement meant to replace them. With the recount nearly finished, silence and disclosure offer different versions of the same betrayal."
  }
]);
